name: Build LaTeX document
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: cd
        run: cd "./paper"
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: ./paper/main.tex
          compiler: pdflatex
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: ./paper/main.aux
          compiler: bibtex
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: ./paper/main.tex
          compiler: pdflatex
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: ./paper/main.tex
          compiler: pdflatex
      - uses: actions/upload-artifact@v3
        with:
          name: main
          path: ${{ github.workspace }}/paper/main.pdf
          if-no-files-found: error
          retention-days: 7
